apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-db
spec:
  serviceName: mssql-db
  replicas: 1
  selector:
    matchLabels:
      app: mssql-db
  template:
    metadata:
      labels:
        app: mssql-db
    spec:
      containers:
        - name: mssql-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: MSSQL_PID
              value: "Developer"
            - name: MSSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USER
          ports:
            - containerPort: 1433
  volumeClaimTemplates:
    - metadata:
        name: mssql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
